apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-openstack-exporter
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "13"
spec:
  project: default
  source:
    repoURL: https://github.com/esmacancs/openstack-gitops.git
    targetRevision: main
    path: charts/prometheus-openstack-exporter
    helm:
      valueFiles:
        - https://raw.githubusercontent.com/esmacancs/openstack-gitops/main/helm-values/openstack-lab-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: openstack
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
