apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openstack
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/openstack/openstack-helm.git
    targetRevision: master
    path: .
    helm:
      valueFiles:
        - https://raw.githubusercontent.com/esmacancs/openstack-gitops/refs/heads/main/argocd/openstack-lab-values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: openstack

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

