helm3_hook: false

pod:
  replicas:
    server: 1

volume:
  class_name: general
  size: 5Gi

conf:
  rabbitmq:
    cluster_partition_handling: autoheal



mariadb:
  volume:
    enabled: false
  pod:
    replicas:
      server: 1

memcached:
  replicas: 1

keystone:
  pod:
    replicas:
      api: 1
  bootstrap:
    enabled: true
keystone-resources:
    enabled: true

glance:
  storage:
    type: memory
  pod:
    replicas:
      api: 1

nova:
  nova_compute:
    enabled: false
  pod:
    replicas:
      api: 1
      conductor: 1
      scheduler: 1

neutron:
  neutron_agent:
    enabled: false
  pod:
    replicas:
      server: 1

horizon:
  replicaCount: 1
  conf:
    horizon:
      branding:
        logo: "PHN2ZyB3aWR0aD0iMjAwIiBoZWlnaHQ9IjUwIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciPgogIDxkZWZzPgogICAgPGxpbmVhckdyYWRpZW50IGlkPSJncmFkMSIgeDE9IjAlIiB5MT0iMCUiIHgyPSIxMDAlIiB5Mj0iMCUiPgogICAgICA8c3RvcCBvZmZzZXQ9IjAlIiBzdHlsZT0ic3RvcC1jb2xvcjojMWUzYThhO3N0b3Atb3BhY2l0eToxIiAvPgogICAgICA8c3RvcCBvZmZzZXQ9IjEwMCUiIHN0eWxlPSJzdG9wLWNvbG9yOiMzYjgyZjY7c3RvcC1vcGFjaXR5OjEiIC8+CiAgICA8L2xpbmVhckdyYWRpZW50PgogIDwvZGVmcz4KICA8cmVjdCB3aWR0aD0iMjAwIiBoZWlnaHQ9IjUwIiBmaWxsPSJ1cmwoI2dyYWQxKSIgcng9IjUiLz4KICA8dGV4dCB4PSIxMDAiIHk9IjMyIiBmb250LWZhbWlseT0iQXJpYWwsIHNhbnMtc2VyaWYiIGZvbnQtc2l6ZT0iMTgiIGZvbnQtd2VpZ2h0PSJib2xkIiBmaWxsPSIjRkZGRkZGIiB0ZXh0LWFuY2hvcj0ibWlkZGxlIj5UcmlzaE9yYTwvdGV4dD4KPC9zdmc+"
        logo_splash: "PHN2ZyB3aWR0aD0iMjAwIiBoZWlnaHQ9IjUwIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciPgogIDxkZWZzPgogICAgPGxpbmVhckdyYWRpZW50IGlkPSJncmFkMSIgeDE9IjAlIiB5MT0iMCUiIHgyPSIxMDAlIiB5Mj0iMCUiPgogICAgICA8c3RvcCBvZmZzZXQ9IjAlIiBzdHlsZT0ic3RvcC1jb2xvcjojMWUzYThhO3N0b3Atb3BhY2l0eToxIiAvPgogICAgICA8c3RvcCBvZmZzZXQ9IjEwMCUiIHN0eWxlPSJzdG9wLWNvbG9yOiMzYjgyZjY7c3RvcC1vcGFjaXR5OjEiIC8+CiAgICA8L2xpbmVhckdyYWRpZW50PgogIDwvZGVmcz4KICA8cmVjdCB3aWR0aD0iMjAwIiBoZWlnaHQ9IjUwIiBmaWxsPSJ1cmwoI2dyYWQxKSIgcng9IjUiLz4KICA8dGV4dCB4PSIxMDAiIHk9IjMyIiBmb250LWZhbWlseT0iQXJpYWwsIHNhbnMtc2VyaWYiIGZvbnQtc2l6ZT0iMTgiIGZvbnQtd2VpZ2h0PSJib2xkIiBmaWxsPSIjRkZGRkZGIiB0ZXh0LWFuY2hvcj0ibWlkZGxlIj5UcmlzaE9yYTwvdGV4dD4KPC9zdmc+"
  manifests:
    configmap_logo: true
