rabbitmq:
  volume:
    enabled: false   # disable PVC for lab
  pod:
    replicas:
      server: 1

mariadb:
  volume:
    enabled: false
  pod:
    replicas:
      server: 1

memcached:
  replicas: 1

keystone:
  pod:
    replicas:
      api: 1
  bootstrap:
    enabled: true

glance:
  storage:
    type: memory
  pod:
    replicas:
      api: 1

nova:
  nova_compute:
    enabled: false
  pod:
    replicas:
      api: 1
      conductor: 1
      scheduler: 1

neutron:
  neutron_agent:
    enabled: false
  pod:
    replicas:
      server: 1

horizon:
  replicaCount: 1
