# =========================
# Global (Lab)
# =========================
conf:
  logging:
    root:
      level: DEBUG

# =========================
# MariaDB
# =========================
mariadb:
  volume:
    enabled: false
  pod:
    replicas:
      server: 1

# =========================
# RabbitMQ
# =========================
rabbitmq:
  volume:
    enabled: false
  pod:
    replicas:
      server: 1

# =========================
# Memcached
# =========================
memcached:
  replicas: 1

# =========================
# Keystone
# =========================
keystone:
  pod:
    replicas:
      api: 1
  bootstrap:
    enabled: true
  conf:
    keystone:
      DEFAULT:
        debug: true

# =========================
# Glance (memory backend)
# =========================
glance:
  storage:
    type: memory
  pod:
    replicas:
      api: 1
  conf:
    glance:
      DEFAULT:
        debug: true

# =========================
# Nova (API only)
# =========================
nova:
  nova_compute:
    enabled: false
  pod:
    replicas:
      api: 1
      conductor: 1
      scheduler: 1
  conf:
    nova:
      DEFAULT:
        debug: true
        compute_driver: ironic.IronicDriver

# =========================
# Neutron (API only)
# =========================
neutron:
  neutron_agent:
    enabled: false
  pod:
    replicas:
      server: 1
  conf:
    neutron:
      DEFAULT:
        debug: true
        core_plugin: ml2

# =========================
# Horizon
# =========================
horizon:
  replicaCount: 1
  conf:
    horizon:
      DEBUG: true

